package org.example.models;

import com.itextpdf.text.*;

import java.util.Date;


public class ReservationTicket {
    public static String FILE = System.getProperty("user.dir") + "/reservation_ticket.pdf";
    public static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    public static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    public static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    public static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);


    public static void addMetaData(Document document) {
        document.addTitle("Reservation");

    }

    public static void addTitlePage(Document document, Hotel hotel, String client, Reservation resa)
            throws DocumentException {
        Paragraph preface = new Paragraph();
        // We add one empty line
        addEmptyLine(preface, 1);
        // Lets write a big header
        preface.add(new Paragraph("Merci pour la reservation " + client + " !", catFont));
        addEmptyLine(preface, 1);

        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Reservation de : " + client + new Date(),
                smallBold));

        addEmptyLine(preface, 2);


        preface.add(new Paragraph(
                "Hotel: " + hotel.getName()));


        preface.add(new Paragraph(
                "Chambre " + resa.getRoom().getNumber() + " | Arrive: " + resa.getDateIn().toString() + " | Depart: " + resa.getDateOut().toString(), smallBold
        ));
        document.add(preface);
        document.newPage();
    }


    public static void createList(Section subCatPart) {
        List list = new List(true, false, 10);
        list.add(new ListItem("First point"));
        list.add(new ListItem("Second point"));
        list.add(new ListItem("Third point"));
        subCatPart.add(list);
    }

    public static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
}
